### PR TITLE
Add Multitenant Support

### PR DESCRIPTION
**Pull request by watermelonjam**
On this branch I've added basic multitenant support.  Since the dictionary views are different for that, I just used a simple config file boolean to use different sql.  I have trouble reading SQL as java string one-liners, so I also added support for loading the SQL at start time from classpath resources.

Other than that, added a couple of debugging logs and removed some swallowed exceptions to get stack traces back.

Sorry about the excessive little commits, I had to shuttle code back and forth between the system I was developing on and the system I run kafka on.

### CODE REVIEW

**Comment by erdemcer** [comment]
Hi,
Thanks for contributing, because of overload i could not check your update. I will review and update you .
Thanks

**Comment by NISH1001** [comment]
@watermelonjam I just tested the PR in with code from your repo. I am not getting any changes to the kafka consumer. Are you sure this works? 
I looked into the POM file and checked the kafka version. So, I am using the same version as mentioned.
Here's my config file for oracle:
```
name=oracle-logminer-connector
connector.class=com.ecer.kafka.connect.oracle.OracleSourceConnector
db.name.alias=test
tasks.max=1
topic=cdctest
db.name=ORCLCDB
db.hostname=localhost
db.port=1521
db.user=striim
db.user.password=striim
db.fetch.size=1
table.whitelist=striim.info
parse.dml.data=true
reset.offset=false
multitenant=true
```

**Comment by pmpetit** [comment]
Hello, you should use
table.whitelist=STRIIM.INFO, because objects in oracle are in uppercase.

**Comment by NISH1001** [comment]
@pmpetit  Thanks. It's working now. I have been working on a similar connector source in python that uses logminer. It too has flexibility of producer/consumer threads. So, in my tool it works regardless of the schema.table name being upper/lower.

This java connector in the PR is working now. Thanks.

**Comment by Semprini** [comment]
@nish1001 is there a repo for your python logminer code?

**Comment by NISH1001** [comment]
@Semprini Sorry I haven't pushed to any remote repository right now. I will in near future once I fix "things".

**Comment by Feeeenng** [comment]
@NISH1001 Is the problem solved now? I very much hope that you can submit code about python use logminer.

**Comment by NISH1001** [comment]
@Feeeenng  yes the problem is solved. The python source code is not optimized and it needs constant polling. Unoptmized in a sense it cannot handle a large number of records for now. :)

**Pull request merged**
